baseurl = "http://www.jasondsouza.org"
languageCode = "en-us"
title = "Jason Dsouza"
MetaDataFormat = "toml"

[author]
    name = "Jason Dsouza"

[params]
    # Default page metadata, used when the specific page doesn't set its own.
    defaultDescription = ""
    defaultKeywords = "Musings, current projects and more about me, Jason Dsouza!"

    # Changes sidebar background and link/accent colours.
    # This also works: "theme-base-0c layout-reverse", or just "layout-reverse".
    theme = ""

    # Select a syntax highight.
    highlight = "solarized_dark"

    # Tagline to display under the author name in the sidebar, keep it short.
    tagline = "Engineer, Hacker, Sculptor"

    # Metadata used to drive integrations.
    googleAuthorship = ""
    googleAnalytics = ""
    gravatarHash = "9a12ad5645a3517bbe0fe067985d13ad"

    # Sidebar social links, avoid enabling too many of these if possible.
    github = "https://github.com/jasonrdsouza"
    twitter = "https://twitter.com/jasonrdsouza"
    googleplus = "https://google.com/+JasonDSouza0"
    linkedin = "https://www.linkedin.com/in/jasonrdsouza"
    facebook = ""
