// Auto-generated from index.html.
// DO NOT EDIT.

library index_html;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'dart:html';
import 'package:widget/widget.dart';


// Original code


String test = "";

void main() {
  test = "Hello world";
}


// Additional generated code
void init_autogenerated() {
  var _root = autogenerated.document.body;
  var __e1;
  var __t = new autogenerated.Template(_root);
  __e1 = _root.nodes[1].nodes[11].nodes[1].nodes[3];
  var __binding0 = __t.contentBind(() => test, false);
  __e1.nodes.add(__binding0);
  __t.create();
  __t.insert();
}

//@ sourceMappingURL=index.dart.map