name: jasonrdsouza.github.io

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cork_site: ^3.1.1
  build: any

dev_dependencies:
  build_runner: any
  build_web_compilers: any

cork_rss:
  title: "Jason Dsouza's Blog"
  description: "Personal thoughts, ruminations, and rants"
  base_url: "https://jasondsouza.org"
  language: "en-us"
  author:
    name: "Jason Dsouza"
    email: "jasonrdsouza@gmail.com"
